Repository IBAS-DEV-PROJECT/IDS_backend, pull requests merged in 2025-03, with the labels that each got.

#15 JwtAuthenticaiton 구현
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/userInfo/OAuth2UserInfoAuthentication.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/token/TokenAuthenticationResult.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/token/jwtUtils/JwtAuthenticationProvider.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/token/jwtUtils/JwtAuthenticationResult.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/token/jwtUtils/JwtAuthenticationToken.java
Labels: feature

#25 Feature/#20
  application.pid
  build.gradle
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/domain/Content.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/domain/ContentNotFoundException.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/domain/ShareStatistics.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/dto/ShareTrackingRequest.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/dto/SocialShareRequest.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/dto/SocialShareResponse.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/repository/ContentRepository.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/repository/ShareStatisticsRepository.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/InstagramSocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/KakaoSocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/SocialShareService.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/SocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/XSocialShareServiceImpl.java
  module_oauth/src/main/java/resource/application.yml
  resource-server/src/main/java/com/example/config/AppConfig.java
  resource-server/src/main/java/com/example/web/SocialShareController.java
  resource-server/src/main/java/com/example/web/TestController.java
  resource-server/src/main/resources/application.yml
Labels: feature

#26 Feature/#20
  .github/workflows/ci.yml
  .github/workflows/spotless-check.yml
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/InstagramSocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/KakaoSocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/SocialShareService.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/SocialShareServiceImpl.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/usecase/XSocialShareServiceImpl.java
  resource-server/src/main/java/com/example/web/SocialShareController.java
Labels: enhancement, feature

#28 feature#23: 음악 추천 기능 컨트롤러 수정 완료
  .github/pull_request_template.md
  resource-server/src/main/java/com/example/web/MBTIController.java
Labels: enhancement, feature

#30 예시 ErrorCode에서 프로젝트에 맞게 수정
  application.pid
  module_oauth/src/main/java/com/spoti/api/auth/domain/error/ErrorCode.java
Labels: enhancement

#37 Fix/#36 공유 관련 기능 수정
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/domain/Content.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/repository/ContentRepository.java
  module_oauth/src/main/java/com/spoti/api/auth/domain/oauth2/socialShare/repository/ShareStatisticsRepository.java
Labels: fix

#38 feat(qna, progress): add DTOs, domain models, repositories, and use cases
  resource-server/src/main/java/com/example/config/SwaggerConfig.java
  resource-server/src/main/java/com/example/web/QnAController.java
  resource-server/src/main/java/com/example/web/TestProgressController.java
  resource-server/src/main/java/com/example/web/progress/domain/Participant.java
  resource-server/src/main/java/com/example/web/progress/domain/TestProgress.java
  resource-server/src/main/java/com/example/web/progress/dto/ParticipantCountDTO.java
  resource-server/src/main/java/com/example/web/progress/repository/ParticipantRepository.java
  resource-server/src/main/java/com/example/web/progress/repository/TestProgressRepository.java
  resource-server/src/main/java/com/example/web/progress/usecase/TestProgressService.java
  resource-server/src/main/java/com/example/web/qna/domain/Answer.java
  resource-server/src/main/java/com/example/web/qna/domain/Question.java
  resource-server/src/main/java/com/example/web/qna/dto/AnswerDTO.java
  resource-server/src/main/java/com/example/web/qna/dto/QuestionDTO.java
  resource-server/src/main/java/com/example/web/qna/repository/AnswerRepository.java
  resource-server/src/main/java/com/example/web/qna/repository/QuestionRepository.java
  resource-server/src/main/java/com/example/web/qna/usecase/QnAService.java
Labels: enhancement
